version: "3.9"

services:
  database:
    image: postgres:15
    container_name: ztpai_postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      # - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: php:8.2-cli
    container_name: ztpai_symfony
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./backend/config/jwt:/app/config/jwt
    working_dir: /app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - database

  frontend:
    image: node:20
    container_name: ztpai_react
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

volumes:
  postgres_data:
