nelmio_api_doc:
    documentation:
        info:
            title: API Dokumentacja
            description: "Dokumentacja API aplikacji"
            version: 1.0.0
        paths:
            /api/login:
                post:
                    tags: ["Auth"]
                    summary: "Logowanie użytkownika"
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        login:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        200:
                            description: "Zwraca token JWT"
                        401:
                            description: "Nieprawidłowe dane logowania"
