nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] # Dopuszcza frontend działający na localhost:3000
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api/':  # Obsługa CORS dla endpointów zaczynających się od /api/
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Type', 'Authorization']
            max_age: 3600
