security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]  # 👈 ROLE_ADMIN ma automatycznie dostęp jako ROLE_USER
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login$
            stateless: true
            provider: app_user_provider
            security: false

        register:
            pattern: ^/api/register$
            security: false

        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
